#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Apartments.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="E_APARTMENT")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUSTOMER_DETAIL(CUSTOMER_DETAIL instance);
    partial void UpdateCUSTOMER_DETAIL(CUSTOMER_DETAIL instance);
    partial void DeleteCUSTOMER_DETAIL(CUSTOMER_DETAIL instance);
    partial void InsertROLL(ROLL instance);
    partial void UpdateROLL(ROLL instance);
    partial void DeleteROLL(ROLL instance);
    partial void InsertRELATIONSHIP(RELATIONSHIP instance);
    partial void UpdateRELATIONSHIP(RELATIONSHIP instance);
    partial void DeleteRELATIONSHIP(RELATIONSHIP instance);
    partial void InsertCUSTOMER_RELATION(CUSTOMER_RELATION instance);
    partial void UpdateCUSTOMER_RELATION(CUSTOMER_RELATION instance);
    partial void DeleteCUSTOMER_RELATION(CUSTOMER_RELATION instance);
    partial void InsertAPARTMENT_CLASS(APARTMENT_CLASS instance);
    partial void UpdateAPARTMENT_CLASS(APARTMENT_CLASS instance);
    partial void DeleteAPARTMENT_CLASS(APARTMENT_CLASS instance);
    partial void InsertSYSTEM_USERS_DETAIL(SYSTEM_USERS_DETAIL instance);
    partial void UpdateSYSTEM_USERS_DETAIL(SYSTEM_USERS_DETAIL instance);
    partial void DeleteSYSTEM_USERS_DETAIL(SYSTEM_USERS_DETAIL instance);
    partial void InsertCUSTOMER_WATING_LIST(CUSTOMER_WATING_LIST instance);
    partial void UpdateCUSTOMER_WATING_LIST(CUSTOMER_WATING_LIST instance);
    partial void DeleteCUSTOMER_WATING_LIST(CUSTOMER_WATING_LIST instance);
    partial void InsertCUSTOMER_COMMENT(CUSTOMER_COMMENT instance);
    partial void UpdateCUSTOMER_COMMENT(CUSTOMER_COMMENT instance);
    partial void DeleteCUSTOMER_COMMENT(CUSTOMER_COMMENT instance);
    partial void InsertPAYMENT_METHOD(PAYMENT_METHOD instance);
    partial void UpdatePAYMENT_METHOD(PAYMENT_METHOD instance);
    partial void DeletePAYMENT_METHOD(PAYMENT_METHOD instance);
    partial void InsertAPARTMENT(APARTMENT instance);
    partial void UpdateAPARTMENT(APARTMENT instance);
    partial void DeleteAPARTMENT(APARTMENT instance);
    partial void InsertAPARTMENT_LEASE(APARTMENT_LEASE instance);
    partial void UpdateAPARTMENT_LEASE(APARTMENT_LEASE instance);
    partial void DeleteAPARTMENT_LEASE(APARTMENT_LEASE instance);
    partial void InsertPAYMENT(PAYMENT instance);
    partial void UpdatePAYMENT(PAYMENT instance);
    partial void DeletePAYMENT(PAYMENT instance);
    partial void InsertAPARTMENT_NAME(APARTMENT_NAME instance);
    partial void UpdateAPARTMENT_NAME(APARTMENT_NAME instance);
    partial void DeleteAPARTMENT_NAME(APARTMENT_NAME instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::E_Apartments.Properties.Settings.Default.E_APARTMENTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUSTOMER_DETAIL> CUSTOMER_DETAILs
		{
			get
			{
				return this.GetTable<CUSTOMER_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<ROLL> ROLLs
		{
			get
			{
				return this.GetTable<ROLL>();
			}
		}
		
		public System.Data.Linq.Table<RELATIONSHIP> RELATIONSHIPs
		{
			get
			{
				return this.GetTable<RELATIONSHIP>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER_RELATION> CUSTOMER_RELATIONs
		{
			get
			{
				return this.GetTable<CUSTOMER_RELATION>();
			}
		}
		
		public System.Data.Linq.Table<APARTMENT_CLASS> APARTMENT_CLASSes
		{
			get
			{
				return this.GetTable<APARTMENT_CLASS>();
			}
		}
		
		public System.Data.Linq.Table<SYSTEM_USERS_DETAIL> SYSTEM_USERS_DETAILs
		{
			get
			{
				return this.GetTable<SYSTEM_USERS_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER_WATING_LIST> CUSTOMER_WATING_LISTs
		{
			get
			{
				return this.GetTable<CUSTOMER_WATING_LIST>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER_COMMENT> CUSTOMER_COMMENTs
		{
			get
			{
				return this.GetTable<CUSTOMER_COMMENT>();
			}
		}
		
		public System.Data.Linq.Table<PAYMENT_METHOD> PAYMENT_METHODs
		{
			get
			{
				return this.GetTable<PAYMENT_METHOD>();
			}
		}
		
		public System.Data.Linq.Table<APARTMENT> APARTMENTs
		{
			get
			{
				return this.GetTable<APARTMENT>();
			}
		}
		
		public System.Data.Linq.Table<APARTMENT_LEASE> APARTMENT_LEASEs
		{
			get
			{
				return this.GetTable<APARTMENT_LEASE>();
			}
		}
		
		public System.Data.Linq.Table<PAYMENT> PAYMENTs
		{
			get
			{
				return this.GetTable<PAYMENT>();
			}
		}
		
		public System.Data.Linq.Table<APARTMENT_NAME> APARTMENT_NAMEs
		{
			get
			{
				return this.GetTable<APARTMENT_NAME>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER_DETAIL")]
	public partial class CUSTOMER_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FULL_NAME;
		
		private string _SURNAME;
		
		private string _NIC;
		
		private System.Nullable<int> _PHONE_NO;
		
		private System.Nullable<int> _TELEPHONE_NO;
		
		private string _ADDRESS;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _E_NAME;
		
		private System.Nullable<int> _E_PHONE;
		
		private System.Nullable<int> _CREATE_BY;
		
		private System.Nullable<System.DateTime> _CREATE_DATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFULL_NAMEChanging(string value);
    partial void OnFULL_NAMEChanged();
    partial void OnSURNAMEChanging(string value);
    partial void OnSURNAMEChanged();
    partial void OnNICChanging(string value);
    partial void OnNICChanged();
    partial void OnPHONE_NOChanging(System.Nullable<int> value);
    partial void OnPHONE_NOChanged();
    partial void OnTELEPHONE_NOChanging(System.Nullable<int> value);
    partial void OnTELEPHONE_NOChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnE_NAMEChanging(string value);
    partial void OnE_NAMEChanged();
    partial void OnE_PHONEChanging(System.Nullable<int> value);
    partial void OnE_PHONEChanged();
    partial void OnCREATE_BYChanging(System.Nullable<int> value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATE_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATE_TIMEChanged();
    #endregion
		
		public CUSTOMER_DETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_NAME", DbType="NVarChar(50)")]
		public string FULL_NAME
		{
			get
			{
				return this._FULL_NAME;
			}
			set
			{
				if ((this._FULL_NAME != value))
				{
					this.OnFULL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FULL_NAME = value;
					this.SendPropertyChanged("FULL_NAME");
					this.OnFULL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURNAME", DbType="NVarChar(50)")]
		public string SURNAME
		{
			get
			{
				return this._SURNAME;
			}
			set
			{
				if ((this._SURNAME != value))
				{
					this.OnSURNAMEChanging(value);
					this.SendPropertyChanging();
					this._SURNAME = value;
					this.SendPropertyChanged("SURNAME");
					this.OnSURNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIC", DbType="NVarChar(50)")]
		public string NIC
		{
			get
			{
				return this._NIC;
			}
			set
			{
				if ((this._NIC != value))
				{
					this.OnNICChanging(value);
					this.SendPropertyChanging();
					this._NIC = value;
					this.SendPropertyChanged("NIC");
					this.OnNICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NO", DbType="Int")]
		public System.Nullable<int> PHONE_NO
		{
			get
			{
				return this._PHONE_NO;
			}
			set
			{
				if ((this._PHONE_NO != value))
				{
					this.OnPHONE_NOChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NO = value;
					this.SendPropertyChanged("PHONE_NO");
					this.OnPHONE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPHONE_NO", DbType="Int")]
		public System.Nullable<int> TELEPHONE_NO
		{
			get
			{
				return this._TELEPHONE_NO;
			}
			set
			{
				if ((this._TELEPHONE_NO != value))
				{
					this.OnTELEPHONE_NOChanging(value);
					this.SendPropertyChanging();
					this._TELEPHONE_NO = value;
					this.SendPropertyChanged("TELEPHONE_NO");
					this.OnTELEPHONE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(50)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_NAME", DbType="NVarChar(50)")]
		public string E_NAME
		{
			get
			{
				return this._E_NAME;
			}
			set
			{
				if ((this._E_NAME != value))
				{
					this.OnE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._E_NAME = value;
					this.SendPropertyChanged("E_NAME");
					this.OnE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PHONE", DbType="Int")]
		public System.Nullable<int> E_PHONE
		{
			get
			{
				return this._E_PHONE;
			}
			set
			{
				if ((this._E_PHONE != value))
				{
					this.OnE_PHONEChanging(value);
					this.SendPropertyChanging();
					this._E_PHONE = value;
					this.SendPropertyChanged("E_PHONE");
					this.OnE_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="Int")]
		public System.Nullable<int> CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE_TIME
		{
			get
			{
				return this._CREATE_DATE_TIME;
			}
			set
			{
				if ((this._CREATE_DATE_TIME != value))
				{
					this.OnCREATE_DATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE_TIME = value;
					this.SendPropertyChanged("CREATE_DATE_TIME");
					this.OnCREATE_DATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROLL")]
	public partial class ROLL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ROLL1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnROLL1Changing(string value);
    partial void OnROLL1Changed();
    #endregion
		
		public ROLL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ROLL", Storage="_ROLL1", DbType="VarChar(10)")]
		public string ROLL1
		{
			get
			{
				return this._ROLL1;
			}
			set
			{
				if ((this._ROLL1 != value))
				{
					this.OnROLL1Changing(value);
					this.SendPropertyChanging();
					this._ROLL1 = value;
					this.SendPropertyChanged("ROLL1");
					this.OnROLL1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RELATIONSHIP")]
	public partial class RELATIONSHIP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RID;
		
		private string _FamilyMember;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRIDChanging(int value);
    partial void OnRIDChanged();
    partial void OnFamilyMemberChanging(string value);
    partial void OnFamilyMemberChanged();
    #endregion
		
		public RELATIONSHIP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this.OnRIDChanging(value);
					this.SendPropertyChanging();
					this._RID = value;
					this.SendPropertyChanged("RID");
					this.OnRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyMember", DbType="VarChar(50)")]
		public string FamilyMember
		{
			get
			{
				return this._FamilyMember;
			}
			set
			{
				if ((this._FamilyMember != value))
				{
					this.OnFamilyMemberChanging(value);
					this.SendPropertyChanging();
					this._FamilyMember = value;
					this.SendPropertyChanged("FamilyMember");
					this.OnFamilyMemberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER_RELATION")]
	public partial class CUSTOMER_RELATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _RID;
		
		private string _NAME;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.Nullable<int> _CUSTOMER_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRIDChanging(System.Nullable<int> value);
    partial void OnRIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnCUSTOMER_IDChanging(System.Nullable<int> value);
    partial void OnCUSTOMER_IDChanged();
    #endregion
		
		public CUSTOMER_RELATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RID", DbType="Int")]
		public System.Nullable<int> RID
		{
			get
			{
				return this._RID;
			}
			set
			{
				if ((this._RID != value))
				{
					this.OnRIDChanging(value);
					this.SendPropertyChanging();
					this._RID = value;
					this.SendPropertyChanged("RID");
					this.OnRIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_ID", DbType="Int")]
		public System.Nullable<int> CUSTOMER_ID
		{
			get
			{
				return this._CUSTOMER_ID;
			}
			set
			{
				if ((this._CUSTOMER_ID != value))
				{
					this.OnCUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_ID = value;
					this.SendPropertyChanged("CUSTOMER_ID");
					this.OnCUSTOMER_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.APARTMENT_CLASS")]
	public partial class APARTMENT_CLASS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _APARTMENT_CLASS_ID;
		
		private string _CLASS_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPARTMENT_CLASS_IDChanging(int value);
    partial void OnAPARTMENT_CLASS_IDChanged();
    partial void OnCLASS_NAMEChanging(string value);
    partial void OnCLASS_NAMEChanged();
    #endregion
		
		public APARTMENT_CLASS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APARTMENT_CLASS_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int APARTMENT_CLASS_ID
		{
			get
			{
				return this._APARTMENT_CLASS_ID;
			}
			set
			{
				if ((this._APARTMENT_CLASS_ID != value))
				{
					this.OnAPARTMENT_CLASS_IDChanging(value);
					this.SendPropertyChanging();
					this._APARTMENT_CLASS_ID = value;
					this.SendPropertyChanged("APARTMENT_CLASS_ID");
					this.OnAPARTMENT_CLASS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_NAME", DbType="VarChar(50)")]
		public string CLASS_NAME
		{
			get
			{
				return this._CLASS_NAME;
			}
			set
			{
				if ((this._CLASS_NAME != value))
				{
					this.OnCLASS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CLASS_NAME = value;
					this.SendPropertyChanged("CLASS_NAME");
					this.OnCLASS_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYSTEM_USERS_DETAIL")]
	public partial class SYSTEM_USERS_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FULL_NAME;
		
		private string _SURNAME;
		
		private string _NIC;
		
		private System.Nullable<int> _PHONENUMBER;
		
		private System.Nullable<int> _TELEPHONE;
		
		private string _ADDRESS;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _ENAME;
		
		private System.Nullable<int> _EPHONENUMBER;
		
		private string _SYSTEM_USER_NAME;
		
		private string _PASS;
		
		private System.Nullable<int> _ROLE_ID;
		
		private System.Nullable<int> _LOCK_1;
		
		private System.Nullable<System.DateTime> _LAST_LOGIN_DTIME;
		
		private System.Nullable<int> _CREATE_EMP_ID;
		
		private System.Nullable<System.DateTime> _CREATE_DTIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFULL_NAMEChanging(string value);
    partial void OnFULL_NAMEChanged();
    partial void OnSURNAMEChanging(string value);
    partial void OnSURNAMEChanged();
    partial void OnNICChanging(string value);
    partial void OnNICChanged();
    partial void OnPHONENUMBERChanging(System.Nullable<int> value);
    partial void OnPHONENUMBERChanged();
    partial void OnTELEPHONEChanging(System.Nullable<int> value);
    partial void OnTELEPHONEChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnENAMEChanging(string value);
    partial void OnENAMEChanged();
    partial void OnEPHONENUMBERChanging(System.Nullable<int> value);
    partial void OnEPHONENUMBERChanged();
    partial void OnSYSTEM_USER_NAMEChanging(string value);
    partial void OnSYSTEM_USER_NAMEChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnROLE_IDChanging(System.Nullable<int> value);
    partial void OnROLE_IDChanged();
    partial void OnLOCK_1Changing(System.Nullable<int> value);
    partial void OnLOCK_1Changed();
    partial void OnLAST_LOGIN_DTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_LOGIN_DTIMEChanged();
    partial void OnCREATE_EMP_IDChanging(System.Nullable<int> value);
    partial void OnCREATE_EMP_IDChanged();
    partial void OnCREATE_DTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DTIMEChanged();
    #endregion
		
		public SYSTEM_USERS_DETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_NAME", DbType="NVarChar(50)")]
		public string FULL_NAME
		{
			get
			{
				return this._FULL_NAME;
			}
			set
			{
				if ((this._FULL_NAME != value))
				{
					this.OnFULL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FULL_NAME = value;
					this.SendPropertyChanged("FULL_NAME");
					this.OnFULL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURNAME", DbType="NVarChar(50)")]
		public string SURNAME
		{
			get
			{
				return this._SURNAME;
			}
			set
			{
				if ((this._SURNAME != value))
				{
					this.OnSURNAMEChanging(value);
					this.SendPropertyChanging();
					this._SURNAME = value;
					this.SendPropertyChanged("SURNAME");
					this.OnSURNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NIC
		{
			get
			{
				return this._NIC;
			}
			set
			{
				if ((this._NIC != value))
				{
					this.OnNICChanging(value);
					this.SendPropertyChanging();
					this._NIC = value;
					this.SendPropertyChanged("NIC");
					this.OnNICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONENUMBER", DbType="Int")]
		public System.Nullable<int> PHONENUMBER
		{
			get
			{
				return this._PHONENUMBER;
			}
			set
			{
				if ((this._PHONENUMBER != value))
				{
					this.OnPHONENUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONENUMBER = value;
					this.SendPropertyChanged("PHONENUMBER");
					this.OnPHONENUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPHONE", DbType="Int")]
		public System.Nullable<int> TELEPHONE
		{
			get
			{
				return this._TELEPHONE;
			}
			set
			{
				if ((this._TELEPHONE != value))
				{
					this.OnTELEPHONEChanging(value);
					this.SendPropertyChanging();
					this._TELEPHONE = value;
					this.SendPropertyChanged("TELEPHONE");
					this.OnTELEPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="NVarChar(50)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENAME", DbType="NVarChar(50)")]
		public string ENAME
		{
			get
			{
				return this._ENAME;
			}
			set
			{
				if ((this._ENAME != value))
				{
					this.OnENAMEChanging(value);
					this.SendPropertyChanging();
					this._ENAME = value;
					this.SendPropertyChanged("ENAME");
					this.OnENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPHONENUMBER", DbType="Int")]
		public System.Nullable<int> EPHONENUMBER
		{
			get
			{
				return this._EPHONENUMBER;
			}
			set
			{
				if ((this._EPHONENUMBER != value))
				{
					this.OnEPHONENUMBERChanging(value);
					this.SendPropertyChanging();
					this._EPHONENUMBER = value;
					this.SendPropertyChanged("EPHONENUMBER");
					this.OnEPHONENUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEM_USER_NAME", DbType="NVarChar(50)")]
		public string SYSTEM_USER_NAME
		{
			get
			{
				return this._SYSTEM_USER_NAME;
			}
			set
			{
				if ((this._SYSTEM_USER_NAME != value))
				{
					this.OnSYSTEM_USER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SYSTEM_USER_NAME = value;
					this.SendPropertyChanged("SYSTEM_USER_NAME");
					this.OnSYSTEM_USER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="NVarChar(50)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_ID", DbType="Int")]
		public System.Nullable<int> ROLE_ID
		{
			get
			{
				return this._ROLE_ID;
			}
			set
			{
				if ((this._ROLE_ID != value))
				{
					this.OnROLE_IDChanging(value);
					this.SendPropertyChanging();
					this._ROLE_ID = value;
					this.SendPropertyChanged("ROLE_ID");
					this.OnROLE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCK_1", DbType="Int")]
		public System.Nullable<int> LOCK_1
		{
			get
			{
				return this._LOCK_1;
			}
			set
			{
				if ((this._LOCK_1 != value))
				{
					this.OnLOCK_1Changing(value);
					this.SendPropertyChanging();
					this._LOCK_1 = value;
					this.SendPropertyChanged("LOCK_1");
					this.OnLOCK_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_LOGIN_DTIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_LOGIN_DTIME
		{
			get
			{
				return this._LAST_LOGIN_DTIME;
			}
			set
			{
				if ((this._LAST_LOGIN_DTIME != value))
				{
					this.OnLAST_LOGIN_DTIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_LOGIN_DTIME = value;
					this.SendPropertyChanged("LAST_LOGIN_DTIME");
					this.OnLAST_LOGIN_DTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_EMP_ID", DbType="Int")]
		public System.Nullable<int> CREATE_EMP_ID
		{
			get
			{
				return this._CREATE_EMP_ID;
			}
			set
			{
				if ((this._CREATE_EMP_ID != value))
				{
					this.OnCREATE_EMP_IDChanging(value);
					this.SendPropertyChanging();
					this._CREATE_EMP_ID = value;
					this.SendPropertyChanged("CREATE_EMP_ID");
					this.OnCREATE_EMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DTIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DTIME
		{
			get
			{
				return this._CREATE_DTIME;
			}
			set
			{
				if ((this._CREATE_DTIME != value))
				{
					this.OnCREATE_DTIMEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DTIME = value;
					this.SendPropertyChanged("CREATE_DTIME");
					this.OnCREATE_DTIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER_WATING_LIST")]
	public partial class CUSTOMER_WATING_LIST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CUSTOMER_NAME;
		
		private string _NIC;
		
		private System.Nullable<int> _PHONE_NUMBER;
		
		private System.Nullable<System.DateTime> _DATE_TIME;
		
		private System.Nullable<int> _APARTMENT_ID;
		
		private System.Nullable<int> _ADD_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnNICChanging(string value);
    partial void OnNICChanged();
    partial void OnPHONE_NUMBERChanging(System.Nullable<int> value);
    partial void OnPHONE_NUMBERChanged();
    partial void OnDATE_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_TIMEChanged();
    partial void OnAPARTMENT_IDChanging(System.Nullable<int> value);
    partial void OnAPARTMENT_IDChanged();
    partial void OnADD_BYChanging(System.Nullable<int> value);
    partial void OnADD_BYChanged();
    #endregion
		
		public CUSTOMER_WATING_LIST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="NVarChar(50)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIC", DbType="NVarChar(50)")]
		public string NIC
		{
			get
			{
				return this._NIC;
			}
			set
			{
				if ((this._NIC != value))
				{
					this.OnNICChanging(value);
					this.SendPropertyChanging();
					this._NIC = value;
					this.SendPropertyChanged("NIC");
					this.OnNICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE_NUMBER", DbType="Int")]
		public System.Nullable<int> PHONE_NUMBER
		{
			get
			{
				return this._PHONE_NUMBER;
			}
			set
			{
				if ((this._PHONE_NUMBER != value))
				{
					this.OnPHONE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._PHONE_NUMBER = value;
					this.SendPropertyChanged("PHONE_NUMBER");
					this.OnPHONE_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_TIME
		{
			get
			{
				return this._DATE_TIME;
			}
			set
			{
				if ((this._DATE_TIME != value))
				{
					this.OnDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._DATE_TIME = value;
					this.SendPropertyChanged("DATE_TIME");
					this.OnDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APARTMENT_ID", DbType="Int")]
		public System.Nullable<int> APARTMENT_ID
		{
			get
			{
				return this._APARTMENT_ID;
			}
			set
			{
				if ((this._APARTMENT_ID != value))
				{
					this.OnAPARTMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._APARTMENT_ID = value;
					this.SendPropertyChanged("APARTMENT_ID");
					this.OnAPARTMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_BY", DbType="Int")]
		public System.Nullable<int> ADD_BY
		{
			get
			{
				return this._ADD_BY;
			}
			set
			{
				if ((this._ADD_BY != value))
				{
					this.OnADD_BYChanging(value);
					this.SendPropertyChanging();
					this._ADD_BY = value;
					this.SendPropertyChanged("ADD_BY");
					this.OnADD_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER_COMMENT")]
	public partial class CUSTOMER_COMMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _COMMENT;
		
		private System.Nullable<System.DateTime> _DATETIME;
		
		private System.Nullable<int> _STATES;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCOMMENTChanging(string value);
    partial void OnCOMMENTChanged();
    partial void OnDATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATETIMEChanged();
    partial void OnSTATESChanging(System.Nullable<int> value);
    partial void OnSTATESChanged();
    #endregion
		
		public CUSTOMER_COMMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT", DbType="NVarChar(200)")]
		public string COMMENT
		{
			get
			{
				return this._COMMENT;
			}
			set
			{
				if ((this._COMMENT != value))
				{
					this.OnCOMMENTChanging(value);
					this.SendPropertyChanging();
					this._COMMENT = value;
					this.SendPropertyChanged("COMMENT");
					this.OnCOMMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATETIME
		{
			get
			{
				return this._DATETIME;
			}
			set
			{
				if ((this._DATETIME != value))
				{
					this.OnDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._DATETIME = value;
					this.SendPropertyChanged("DATETIME");
					this.OnDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATES", DbType="Int")]
		public System.Nullable<int> STATES
		{
			get
			{
				return this._STATES;
			}
			set
			{
				if ((this._STATES != value))
				{
					this.OnSTATESChanging(value);
					this.SendPropertyChanging();
					this._STATES = value;
					this.SendPropertyChanged("STATES");
					this.OnSTATESChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAYMENT_METHODS")]
	public partial class PAYMENT_METHOD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PAYMENT_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPAYMENT_TYPEChanging(string value);
    partial void OnPAYMENT_TYPEChanged();
    #endregion
		
		public PAYMENT_METHOD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_TYPE", DbType="VarChar(50)")]
		public string PAYMENT_TYPE
		{
			get
			{
				return this._PAYMENT_TYPE;
			}
			set
			{
				if ((this._PAYMENT_TYPE != value))
				{
					this.OnPAYMENT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._PAYMENT_TYPE = value;
					this.SendPropertyChanged("PAYMENT_TYPE");
					this.OnPAYMENT_TYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.APARTMENT")]
	public partial class APARTMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LOCATION;
		
		private System.Nullable<int> _CLASS_ID;
		
		private System.Nullable<int> _APARTMENT_ID;
		
		private System.Nullable<int> _FLOW_AREA;
		
		private System.Nullable<decimal> _APPLICABLE_RENT;
		
		private System.Nullable<decimal> _APPLICABLE_AMOUNT;
		
		private System.Nullable<decimal> _APPLICABLE_DEPOSIT_AMOUNT;
		
		private System.Nullable<int> _APPLICABLE_MAXIMUM_N_F_OCCUP;
		
		private System.Nullable<decimal> _APPLICABLE_RESERVATION_FEE;
		
		private System.Nullable<int> _NUMBER_AVAILABLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnCLASS_IDChanging(System.Nullable<int> value);
    partial void OnCLASS_IDChanged();
    partial void OnAPARTMENT_IDChanging(System.Nullable<int> value);
    partial void OnAPARTMENT_IDChanged();
    partial void OnFLOW_AREAChanging(System.Nullable<int> value);
    partial void OnFLOW_AREAChanged();
    partial void OnAPPLICABLE_RENTChanging(System.Nullable<decimal> value);
    partial void OnAPPLICABLE_RENTChanged();
    partial void OnAPPLICABLE_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnAPPLICABLE_AMOUNTChanged();
    partial void OnAPPLICABLE_DEPOSIT_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnAPPLICABLE_DEPOSIT_AMOUNTChanged();
    partial void OnAPPLICABLE_MAXIMUM_N_F_OCCUPChanging(System.Nullable<int> value);
    partial void OnAPPLICABLE_MAXIMUM_N_F_OCCUPChanged();
    partial void OnAPPLICABLE_RESERVATION_FEEChanging(System.Nullable<decimal> value);
    partial void OnAPPLICABLE_RESERVATION_FEEChanged();
    partial void OnNUMBER_AVAILABLEChanging(System.Nullable<int> value);
    partial void OnNUMBER_AVAILABLEChanged();
    #endregion
		
		public APARTMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(30)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int")]
		public System.Nullable<int> CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this.OnCLASS_IDChanging(value);
					this.SendPropertyChanging();
					this._CLASS_ID = value;
					this.SendPropertyChanged("CLASS_ID");
					this.OnCLASS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APARTMENT_ID", DbType="Int")]
		public System.Nullable<int> APARTMENT_ID
		{
			get
			{
				return this._APARTMENT_ID;
			}
			set
			{
				if ((this._APARTMENT_ID != value))
				{
					this.OnAPARTMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._APARTMENT_ID = value;
					this.SendPropertyChanged("APARTMENT_ID");
					this.OnAPARTMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLOW_AREA", DbType="Int")]
		public System.Nullable<int> FLOW_AREA
		{
			get
			{
				return this._FLOW_AREA;
			}
			set
			{
				if ((this._FLOW_AREA != value))
				{
					this.OnFLOW_AREAChanging(value);
					this.SendPropertyChanging();
					this._FLOW_AREA = value;
					this.SendPropertyChanged("FLOW_AREA");
					this.OnFLOW_AREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICABLE_RENT", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> APPLICABLE_RENT
		{
			get
			{
				return this._APPLICABLE_RENT;
			}
			set
			{
				if ((this._APPLICABLE_RENT != value))
				{
					this.OnAPPLICABLE_RENTChanging(value);
					this.SendPropertyChanging();
					this._APPLICABLE_RENT = value;
					this.SendPropertyChanged("APPLICABLE_RENT");
					this.OnAPPLICABLE_RENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICABLE_AMOUNT", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> APPLICABLE_AMOUNT
		{
			get
			{
				return this._APPLICABLE_AMOUNT;
			}
			set
			{
				if ((this._APPLICABLE_AMOUNT != value))
				{
					this.OnAPPLICABLE_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._APPLICABLE_AMOUNT = value;
					this.SendPropertyChanged("APPLICABLE_AMOUNT");
					this.OnAPPLICABLE_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICABLE_DEPOSIT_AMOUNT", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> APPLICABLE_DEPOSIT_AMOUNT
		{
			get
			{
				return this._APPLICABLE_DEPOSIT_AMOUNT;
			}
			set
			{
				if ((this._APPLICABLE_DEPOSIT_AMOUNT != value))
				{
					this.OnAPPLICABLE_DEPOSIT_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._APPLICABLE_DEPOSIT_AMOUNT = value;
					this.SendPropertyChanged("APPLICABLE_DEPOSIT_AMOUNT");
					this.OnAPPLICABLE_DEPOSIT_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICABLE_MAXIMUM_N_F_OCCUP", DbType="Int")]
		public System.Nullable<int> APPLICABLE_MAXIMUM_N_F_OCCUP
		{
			get
			{
				return this._APPLICABLE_MAXIMUM_N_F_OCCUP;
			}
			set
			{
				if ((this._APPLICABLE_MAXIMUM_N_F_OCCUP != value))
				{
					this.OnAPPLICABLE_MAXIMUM_N_F_OCCUPChanging(value);
					this.SendPropertyChanging();
					this._APPLICABLE_MAXIMUM_N_F_OCCUP = value;
					this.SendPropertyChanged("APPLICABLE_MAXIMUM_N_F_OCCUP");
					this.OnAPPLICABLE_MAXIMUM_N_F_OCCUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICABLE_RESERVATION_FEE", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> APPLICABLE_RESERVATION_FEE
		{
			get
			{
				return this._APPLICABLE_RESERVATION_FEE;
			}
			set
			{
				if ((this._APPLICABLE_RESERVATION_FEE != value))
				{
					this.OnAPPLICABLE_RESERVATION_FEEChanging(value);
					this.SendPropertyChanging();
					this._APPLICABLE_RESERVATION_FEE = value;
					this.SendPropertyChanged("APPLICABLE_RESERVATION_FEE");
					this.OnAPPLICABLE_RESERVATION_FEEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER_AVAILABLE", DbType="Int")]
		public System.Nullable<int> NUMBER_AVAILABLE
		{
			get
			{
				return this._NUMBER_AVAILABLE;
			}
			set
			{
				if ((this._NUMBER_AVAILABLE != value))
				{
					this.OnNUMBER_AVAILABLEChanging(value);
					this.SendPropertyChanging();
					this._NUMBER_AVAILABLE = value;
					this.SendPropertyChanged("NUMBER_AVAILABLE");
					this.OnNUMBER_AVAILABLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.APARTMENT_LEASE")]
	public partial class APARTMENT_LEASE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CUSTOMER_ID;
		
		private System.Nullable<int> _APARTMENT_ID;
		
		private System.Nullable<decimal> _FRIST_RENT_AMOUNT;
		
		private System.Nullable<decimal> _APP_AMOUNT;
		
		private System.Nullable<decimal> _DEPOSITE_AMOUNT;
		
		private System.Nullable<decimal> _APPLICABLE_FEE;
		
		private System.Nullable<System.DateTime> _LEASE_START_DATE;
		
		private System.Nullable<System.DateTime> _END_DATE;
		
		private System.Nullable<System.DateTime> _DUE_DATE;
		
		private string _DESCRIPTION;
		
		private System.Nullable<int> _STATES;
		
		private System.Nullable<int> _CREATE_BY;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private System.Nullable<int> _APPROVED_BY;
		
		private System.Nullable<System.DateTime> _APPROVED_DATE;
		
		private string _PARKING_SPACE_ID;
		
		private string _PARKING_SPACE_EXTRA_ID;
		
		private System.Nullable<decimal> _PARKING_SPACE_EXTRA_MONTHLY_RENTAL;
		
		private System.Nullable<int> _PAYMENT_TYPE_ID;
		
		private System.Nullable<int> _TOTALE_MONTHS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCUSTOMER_IDChanging(System.Nullable<int> value);
    partial void OnCUSTOMER_IDChanged();
    partial void OnAPARTMENT_IDChanging(System.Nullable<int> value);
    partial void OnAPARTMENT_IDChanged();
    partial void OnFRIST_RENT_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnFRIST_RENT_AMOUNTChanged();
    partial void OnAPP_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnAPP_AMOUNTChanged();
    partial void OnDEPOSITE_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnDEPOSITE_AMOUNTChanged();
    partial void OnAPPLICABLE_FEEChanging(System.Nullable<decimal> value);
    partial void OnAPPLICABLE_FEEChanged();
    partial void OnLEASE_START_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLEASE_START_DATEChanged();
    partial void OnEND_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEND_DATEChanged();
    partial void OnDUE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDUE_DATEChanged();
    partial void OnDESCRIPTIONChanging(string value);
    partial void OnDESCRIPTIONChanged();
    partial void OnSTATESChanging(System.Nullable<int> value);
    partial void OnSTATESChanged();
    partial void OnCREATE_BYChanging(System.Nullable<int> value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnAPPROVED_BYChanging(System.Nullable<int> value);
    partial void OnAPPROVED_BYChanged();
    partial void OnAPPROVED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnAPPROVED_DATEChanged();
    partial void OnPARKING_SPACE_IDChanging(string value);
    partial void OnPARKING_SPACE_IDChanged();
    partial void OnPARKING_SPACE_EXTRA_IDChanging(string value);
    partial void OnPARKING_SPACE_EXTRA_IDChanged();
    partial void OnPARKING_SPACE_EXTRA_MONTHLY_RENTALChanging(System.Nullable<decimal> value);
    partial void OnPARKING_SPACE_EXTRA_MONTHLY_RENTALChanged();
    partial void OnPAYMENT_TYPE_IDChanging(System.Nullable<int> value);
    partial void OnPAYMENT_TYPE_IDChanged();
    partial void OnTOTALE_MONTHSChanging(System.Nullable<int> value);
    partial void OnTOTALE_MONTHSChanged();
    #endregion
		
		public APARTMENT_LEASE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_ID", DbType="Int")]
		public System.Nullable<int> CUSTOMER_ID
		{
			get
			{
				return this._CUSTOMER_ID;
			}
			set
			{
				if ((this._CUSTOMER_ID != value))
				{
					this.OnCUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_ID = value;
					this.SendPropertyChanged("CUSTOMER_ID");
					this.OnCUSTOMER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APARTMENT_ID", DbType="Int")]
		public System.Nullable<int> APARTMENT_ID
		{
			get
			{
				return this._APARTMENT_ID;
			}
			set
			{
				if ((this._APARTMENT_ID != value))
				{
					this.OnAPARTMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._APARTMENT_ID = value;
					this.SendPropertyChanged("APARTMENT_ID");
					this.OnAPARTMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRIST_RENT_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FRIST_RENT_AMOUNT
		{
			get
			{
				return this._FRIST_RENT_AMOUNT;
			}
			set
			{
				if ((this._FRIST_RENT_AMOUNT != value))
				{
					this.OnFRIST_RENT_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._FRIST_RENT_AMOUNT = value;
					this.SendPropertyChanged("FRIST_RENT_AMOUNT");
					this.OnFRIST_RENT_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> APP_AMOUNT
		{
			get
			{
				return this._APP_AMOUNT;
			}
			set
			{
				if ((this._APP_AMOUNT != value))
				{
					this.OnAPP_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._APP_AMOUNT = value;
					this.SendPropertyChanged("APP_AMOUNT");
					this.OnAPP_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPOSITE_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> DEPOSITE_AMOUNT
		{
			get
			{
				return this._DEPOSITE_AMOUNT;
			}
			set
			{
				if ((this._DEPOSITE_AMOUNT != value))
				{
					this.OnDEPOSITE_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._DEPOSITE_AMOUNT = value;
					this.SendPropertyChanged("DEPOSITE_AMOUNT");
					this.OnDEPOSITE_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPLICABLE_FEE", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> APPLICABLE_FEE
		{
			get
			{
				return this._APPLICABLE_FEE;
			}
			set
			{
				if ((this._APPLICABLE_FEE != value))
				{
					this.OnAPPLICABLE_FEEChanging(value);
					this.SendPropertyChanging();
					this._APPLICABLE_FEE = value;
					this.SendPropertyChanged("APPLICABLE_FEE");
					this.OnAPPLICABLE_FEEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEASE_START_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> LEASE_START_DATE
		{
			get
			{
				return this._LEASE_START_DATE;
			}
			set
			{
				if ((this._LEASE_START_DATE != value))
				{
					this.OnLEASE_START_DATEChanging(value);
					this.SendPropertyChanging();
					this._LEASE_START_DATE = value;
					this.SendPropertyChanged("LEASE_START_DATE");
					this.OnLEASE_START_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_END_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> END_DATE
		{
			get
			{
				return this._END_DATE;
			}
			set
			{
				if ((this._END_DATE != value))
				{
					this.OnEND_DATEChanging(value);
					this.SendPropertyChanging();
					this._END_DATE = value;
					this.SendPropertyChanged("END_DATE");
					this.OnEND_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DUE_DATE
		{
			get
			{
				return this._DUE_DATE;
			}
			set
			{
				if ((this._DUE_DATE != value))
				{
					this.OnDUE_DATEChanging(value);
					this.SendPropertyChanging();
					this._DUE_DATE = value;
					this.SendPropertyChanged("DUE_DATE");
					this.OnDUE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="NVarChar(100)")]
		public string DESCRIPTION
		{
			get
			{
				return this._DESCRIPTION;
			}
			set
			{
				if ((this._DESCRIPTION != value))
				{
					this.OnDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPTION = value;
					this.SendPropertyChanged("DESCRIPTION");
					this.OnDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATES", DbType="Int")]
		public System.Nullable<int> STATES
		{
			get
			{
				return this._STATES;
			}
			set
			{
				if ((this._STATES != value))
				{
					this.OnSTATESChanging(value);
					this.SendPropertyChanging();
					this._STATES = value;
					this.SendPropertyChanged("STATES");
					this.OnSTATESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="Int")]
		public System.Nullable<int> CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVED_BY", DbType="Int")]
		public System.Nullable<int> APPROVED_BY
		{
			get
			{
				return this._APPROVED_BY;
			}
			set
			{
				if ((this._APPROVED_BY != value))
				{
					this.OnAPPROVED_BYChanging(value);
					this.SendPropertyChanging();
					this._APPROVED_BY = value;
					this.SendPropertyChanged("APPROVED_BY");
					this.OnAPPROVED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVED_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> APPROVED_DATE
		{
			get
			{
				return this._APPROVED_DATE;
			}
			set
			{
				if ((this._APPROVED_DATE != value))
				{
					this.OnAPPROVED_DATEChanging(value);
					this.SendPropertyChanging();
					this._APPROVED_DATE = value;
					this.SendPropertyChanged("APPROVED_DATE");
					this.OnAPPROVED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARKING_SPACE_ID", DbType="NVarChar(50)")]
		public string PARKING_SPACE_ID
		{
			get
			{
				return this._PARKING_SPACE_ID;
			}
			set
			{
				if ((this._PARKING_SPACE_ID != value))
				{
					this.OnPARKING_SPACE_IDChanging(value);
					this.SendPropertyChanging();
					this._PARKING_SPACE_ID = value;
					this.SendPropertyChanged("PARKING_SPACE_ID");
					this.OnPARKING_SPACE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARKING_SPACE_EXTRA_ID", DbType="NVarChar(50)")]
		public string PARKING_SPACE_EXTRA_ID
		{
			get
			{
				return this._PARKING_SPACE_EXTRA_ID;
			}
			set
			{
				if ((this._PARKING_SPACE_EXTRA_ID != value))
				{
					this.OnPARKING_SPACE_EXTRA_IDChanging(value);
					this.SendPropertyChanging();
					this._PARKING_SPACE_EXTRA_ID = value;
					this.SendPropertyChanged("PARKING_SPACE_EXTRA_ID");
					this.OnPARKING_SPACE_EXTRA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARKING_SPACE_EXTRA_MONTHLY_RENTAL", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> PARKING_SPACE_EXTRA_MONTHLY_RENTAL
		{
			get
			{
				return this._PARKING_SPACE_EXTRA_MONTHLY_RENTAL;
			}
			set
			{
				if ((this._PARKING_SPACE_EXTRA_MONTHLY_RENTAL != value))
				{
					this.OnPARKING_SPACE_EXTRA_MONTHLY_RENTALChanging(value);
					this.SendPropertyChanging();
					this._PARKING_SPACE_EXTRA_MONTHLY_RENTAL = value;
					this.SendPropertyChanged("PARKING_SPACE_EXTRA_MONTHLY_RENTAL");
					this.OnPARKING_SPACE_EXTRA_MONTHLY_RENTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_TYPE_ID", DbType="Int")]
		public System.Nullable<int> PAYMENT_TYPE_ID
		{
			get
			{
				return this._PAYMENT_TYPE_ID;
			}
			set
			{
				if ((this._PAYMENT_TYPE_ID != value))
				{
					this.OnPAYMENT_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._PAYMENT_TYPE_ID = value;
					this.SendPropertyChanged("PAYMENT_TYPE_ID");
					this.OnPAYMENT_TYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALE_MONTHS", DbType="Int")]
		public System.Nullable<int> TOTALE_MONTHS
		{
			get
			{
				return this._TOTALE_MONTHS;
			}
			set
			{
				if ((this._TOTALE_MONTHS != value))
				{
					this.OnTOTALE_MONTHSChanging(value);
					this.SendPropertyChanging();
					this._TOTALE_MONTHS = value;
					this.SendPropertyChanged("TOTALE_MONTHS");
					this.OnTOTALE_MONTHSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAYMENTS")]
	public partial class PAYMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<decimal> _AMOUNT;
		
		private System.Nullable<decimal> _ARREARS_AMOUNT;
		
		private System.Nullable<int> _PAYMENT_TYPE;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<int> _RECEIPT_BY;
		
		private System.Nullable<int> _LEASE_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAMOUNTChanging(System.Nullable<decimal> value);
    partial void OnAMOUNTChanged();
    partial void OnARREARS_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnARREARS_AMOUNTChanged();
    partial void OnPAYMENT_TYPEChanging(System.Nullable<int> value);
    partial void OnPAYMENT_TYPEChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnRECEIPT_BYChanging(System.Nullable<int> value);
    partial void OnRECEIPT_BYChanged();
    partial void OnLEASE_IDChanging(System.Nullable<int> value);
    partial void OnLEASE_IDChanged();
    #endregion
		
		public PAYMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this.OnAMOUNTChanging(value);
					this.SendPropertyChanging();
					this._AMOUNT = value;
					this.SendPropertyChanged("AMOUNT");
					this.OnAMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARREARS_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ARREARS_AMOUNT
		{
			get
			{
				return this._ARREARS_AMOUNT;
			}
			set
			{
				if ((this._ARREARS_AMOUNT != value))
				{
					this.OnARREARS_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._ARREARS_AMOUNT = value;
					this.SendPropertyChanged("ARREARS_AMOUNT");
					this.OnARREARS_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_TYPE", DbType="Int")]
		public System.Nullable<int> PAYMENT_TYPE
		{
			get
			{
				return this._PAYMENT_TYPE;
			}
			set
			{
				if ((this._PAYMENT_TYPE != value))
				{
					this.OnPAYMENT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._PAYMENT_TYPE = value;
					this.SendPropertyChanged("PAYMENT_TYPE");
					this.OnPAYMENT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIPT_BY", DbType="Int")]
		public System.Nullable<int> RECEIPT_BY
		{
			get
			{
				return this._RECEIPT_BY;
			}
			set
			{
				if ((this._RECEIPT_BY != value))
				{
					this.OnRECEIPT_BYChanging(value);
					this.SendPropertyChanging();
					this._RECEIPT_BY = value;
					this.SendPropertyChanged("RECEIPT_BY");
					this.OnRECEIPT_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEASE_ID", DbType="Int")]
		public System.Nullable<int> LEASE_ID
		{
			get
			{
				return this._LEASE_ID;
			}
			set
			{
				if ((this._LEASE_ID != value))
				{
					this.OnLEASE_IDChanging(value);
					this.SendPropertyChanging();
					this._LEASE_ID = value;
					this.SendPropertyChanged("LEASE_ID");
					this.OnLEASE_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.APARTMENT_NAME")]
	public partial class APARTMENT_NAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AP_NAME_ID;
		
		private string _APARTMENT_NAME1;
		
		private System.Nullable<int> _ADD_BY;
		
		private System.Nullable<System.DateTime> _ADD_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAP_NAME_IDChanging(int value);
    partial void OnAP_NAME_IDChanged();
    partial void OnAPARTMENT_NAME1Changing(string value);
    partial void OnAPARTMENT_NAME1Changed();
    partial void OnADD_BYChanging(System.Nullable<int> value);
    partial void OnADD_BYChanged();
    partial void OnADD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnADD_DATEChanged();
    #endregion
		
		public APARTMENT_NAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_NAME_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AP_NAME_ID
		{
			get
			{
				return this._AP_NAME_ID;
			}
			set
			{
				if ((this._AP_NAME_ID != value))
				{
					this.OnAP_NAME_IDChanging(value);
					this.SendPropertyChanging();
					this._AP_NAME_ID = value;
					this.SendPropertyChanged("AP_NAME_ID");
					this.OnAP_NAME_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="APARTMENT_NAME", Storage="_APARTMENT_NAME1", DbType="VarChar(50)")]
		public string APARTMENT_NAME1
		{
			get
			{
				return this._APARTMENT_NAME1;
			}
			set
			{
				if ((this._APARTMENT_NAME1 != value))
				{
					this.OnAPARTMENT_NAME1Changing(value);
					this.SendPropertyChanging();
					this._APARTMENT_NAME1 = value;
					this.SendPropertyChanged("APARTMENT_NAME1");
					this.OnAPARTMENT_NAME1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_BY", DbType="Int")]
		public System.Nullable<int> ADD_BY
		{
			get
			{
				return this._ADD_BY;
			}
			set
			{
				if ((this._ADD_BY != value))
				{
					this.OnADD_BYChanging(value);
					this.SendPropertyChanging();
					this._ADD_BY = value;
					this.SendPropertyChanged("ADD_BY");
					this.OnADD_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> ADD_DATE
		{
			get
			{
				return this._ADD_DATE;
			}
			set
			{
				if ((this._ADD_DATE != value))
				{
					this.OnADD_DATEChanging(value);
					this.SendPropertyChanging();
					this._ADD_DATE = value;
					this.SendPropertyChanged("ADD_DATE");
					this.OnADD_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
